### ISSUE TITLE
custom fonts and sizes

### ISSUE THREAD

**Issue by user1850133** [goldendict/goldendict#1154]
there should be a way to change the various fonts used in the goldendict control panel, especially the search field and the size of the box. In linux the menu fonts are managed by the desktop environment, so this is fine for that.

**Comment by nikita-moor** [comment]
I think it's defined in the [qt-style.css][1], and following the wiki users [could redefine their styles][2].

[1]: https://github.com/goldendict/goldendict/blob/48e850c7ec11d83cba7499f7fdce377ef3849bbb/qt-style.css
[2]: http://goldendict.org/wiki/index.php/FAQ

**Comment by user1850133** [comment]
> I think it's defined in the [qt-style.css](https://github.com/goldendict/goldendict/blob/48e850c7ec11d83cba7499f7fdce377ef3849bbb/qt-style.css), and following the wiki users [could redefine their styles](http://goldendict.org/wiki/index.php/FAQ).

does it work with version 1.5.0-RC2? it tried it and it seems not.

**Comment by latin-dict** [comment]
It does work for me (GoldenDict 1.5.0-RC2-445, Linux):

* close GoldenDict
* go to the folder `~/.goldendict/` (file `article-style.css` is there)
* create new file `qt-style.css`
* add styling information (see below)
* execute GoldenDict

Now is an example of styling searchPane—blue text on pink background:

```css
MainWindow #searchPane #translateLine {
  background: pink;
  color: darkblue;
  font-size: 20px;
}
```

![Screenshot_2021-01-01_19-10-35](https://user-images.githubusercontent.com/73873396/103442197-20c32580-4c65-11eb-9420-32e0848442c2.png)

**Comment by user1850133** [comment]
> It does work for me (GoldenDict 1.5.0-RC2-445; Linux):
>     * close GoldenDict
>     * go to the folder `~/.goldendict/` (file `article-style.css` is there)
>     * create new file `qt-style.css`
>     * add styling information (see below)
>     * execute GoldenDict
> Now is an example of styling searchPane—blue text on pink background:
> 
> ```css
> MainWindow #searchPane #translateLine {
>   background: pink;
>   color: darkblue;
>   font-size: 20px;
> }
> ```
[ ... ]
yes, it does. For your example, it also affects the font size of the dictionaries group selection field. Once set so, did you ever try alt++, and alt+-? the font size in that selection field shrinks to something extremely tiny when zoomed-in of one step.

What's the keyword to select the text of article panes?

**Comment by latin-dict** [comment]
> it also affects the font size of the dictionaries group selection field

Yeah, they are linked somehow. This ComboBox is created dynamically in the code, so CSS styles are not applicable.

> What's the keyword to select the text of article panes?

I'm not sure that I understand your question, is it related to the GUI or formatting of the articles? Could you demonstrate it on a screenshot? Elements of the main window are defined in [mainwindow.ui](https://github.com/goldendict/goldendict/blob/master/mainwindow.ui), use Qt Designer to open it.

**Comment by user1850133** [comment]
> I'm not sure that I understand your question, is it related to GUI styling or formatting of the articles? Could you demonstrate it on a screenshot? Elements of the main window are defined in [mainwindow.ui](https://github.com/goldendict/goldendict/blob/master/mainwindow.ui), use Qt Designer to open it.
i mean article tabs label in the nail. Many articles can be opened at the same time and each tab's nail has the title of the article opened. I quickly tried with Qt Designer to find that keyword, I think it it currentTabText.

**Comment by latin-dict** [comment]
> article tabs label in the nail

See [qt-style-st-lingoes-blue.css](https://github.com/goldendict/goldendict/blob/master/qt-style-st-lingoes-blue.css):

```css
MainWindow #centralWidget QTabBar::tab {
    border: 1px solid #667B9B;
    border-bottom-color: #667B9B;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    padding: 1px 3px;
    margin-left: 1px;
    margin-top: 2px;
    margin-bottom: 2px;
    background-color: #CFDDF0;
    color: darkslategray;
}
```

![Screenshot_2021-01-03_20-07-52](https://user-images.githubusercontent.com/73873396/103484371-6f0c2c00-4dff-11eb-97c9-fb7ec9b93f53.png)
