### ISSUE TITLE
Default CSS for NHK Nihongo Hatsuon Akusento Jiten (NHK Japanese Accentuation Dictionary)

### ISSUE THREAD

**Issue by leoboiko** [goldendict/goldendict#862]
Hi,

Do you do built-in CSS styles for specific dictionaries? If so, you might consider make images `display: inline` for the EPWING dictionary with the title attribute  `ＮＨＫ　日本語発音アクセント辞典`.  It uses images to represent accented Japanese characters, and under the default style, it's unreadable in GoldenDict, since each character breaks into a separate line.  Also, its images should  be scaled relatively to the text point size.

I found the following to work ok:
```css
p.epwing_image {
  display: inline;
}
img {
  height: 1.5em;
  width: auto;
}
```

Before:

![nhk_before](https://user-images.githubusercontent.com/74593/27787767-45ee854e-5fe6-11e7-9153-979cb12f840c.png)

(Don't mind  the excessively small text size; that's a separate issue, related to Goldendict not playing nice with HiDPI displays on Linux.)

After:

![nhk_after](https://user-images.githubusercontent.com/74593/27787786-56dd01be-5fe6-11e7-82ca-b7c6b8798813.png)

**Comment by mjuzikfrik** [comment]
@leoboiko could you please tell me where do put the code to make it display correctly?

**Comment by leoboiko** [comment]
@mjuzikfrik Hi,

I don't know how to set it for a specific dictionary, so I just set it for all (since I don't use other image-based dictionaries).  My NHK is from the Epwing release.  I use Linux, and I added this to the file `~/.goldendict/article-style.css`:

```css
p.epwing_image {
  display: inline;
}

/* for NHK */
img {
  height: 1.5em;;
  width: auto;
}
```

In Windows, it seems that `article-style.css` goes in your `GoldenDict` folder.

**Comment by mjuzikfrik** [comment]
Thanks, got it to work.

**Comment by koihia** [comment]
The workaround can be applied to some specific dictionaries by their id instead of all dictionaries.
You can inspect the dictionary title to find them.

```css
#gdfrom-db08a9fd68bf3be725e13be47ae45239 p.epwing_image {
  display: inline;
}
#gdfrom-db08a9fd68bf3be725e13be47ae45239 p.epwing_image > img {
  height: 1.5em;
  width: auto;
}
```
